/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wonproj2;

import java.awt.event.ActionListener;

/**
 *
 * @author Minhawn
 */
public class WonProj2View extends javax.swing.JFrame {

    /**
     * Creates new form WonProj2View
     */
    public WonProj2View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        File_List = new javax.swing.JTextArea();
        DirSearch = new javax.swing.JTextField();
        DirSearchButton = new javax.swing.JButton();
        FileSearch = new javax.swing.JTextField();
        FileSearchButton = new javax.swing.JButton();
        Directory_Label = new javax.swing.JLabel();
        FileSearch_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("John's File GUI");
        setResizable(false);

        File_List.setEditable(false);
        File_List.setBackground(new java.awt.Color(0, 0, 0));
        File_List.setColumns(20);
        File_List.setForeground(new java.awt.Color(0, 153, 0));
        File_List.setRows(5);
        jScrollPane1.setViewportView(File_List);

        DirSearch.setText("C:/");
        DirSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirSearchActionPerformed(evt);
            }
        });

        DirSearchButton.setText("Go");
        DirSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirSearchButtonActionPerformed(evt);
            }
        });

        FileSearchButton.setText("Search");
        FileSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileSearchButtonActionPerformed(evt);
            }
        });

        Directory_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Directory_Label.setText("Directory");

        FileSearch_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FileSearch_Label.setText("File Search (Case Sensitive)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(DirSearch)
                    .addComponent(FileSearch)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DirSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(Directory_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FileSearch_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FileSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Directory_Label)
                .addGap(13, 13, 13)
                .addComponent(DirSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DirSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FileSearch_Label)
                .addGap(9, 9, 9)
                .addComponent(FileSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FileSearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DirSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DirSearchActionPerformed

    private void DirSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirSearchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DirSearchButtonActionPerformed

    private void FileSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileSearchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileSearchButtonActionPerformed

    void addOutputDirListener(ActionListener output_Dir)
    {
        DirSearchButton.addActionListener(output_Dir);
    }
    
    void addOutputSearchListener(ActionListener output_Search)
    {
        FileSearchButton.addActionListener(output_Search);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField DirSearch;
    public javax.swing.JButton DirSearchButton;
    private javax.swing.JLabel Directory_Label;
    public javax.swing.JTextField FileSearch;
    public javax.swing.JButton FileSearchButton;
    private javax.swing.JLabel FileSearch_Label;
    public javax.swing.JTextArea File_List;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
